In [27]:
import numpy as np
import numpy.linalg as la

In [24]:
#HW 3.4 Using Inverses to Solve Matrix Equations

a = np.array([[1,1],[1,-1]])
b = np.array([[0,-1],[1,0]])
c = np.array([[-2,-1],[1,-2]])

ainv = np.array([[.5,.5],[.5,-.5]])
binv = np.array([[0,1],[-1,0]])

x1 = ainv @ (c - a - 3*b) @ binv

print(x1)

[[ 0. -3.]
 [-1.  0.]]


In [65]:
#HW 3.5 Right Inverse

I = np.eye(2)
m = np.array([[1,-1,2],
              [1,0,1]])

inter = m @ m.T
inter2 = la.inv(inter)
B = m.T @ inter2
print(B)

[[-0.33333333  1.        ]
 [-0.66666667  1.        ]
 [ 0.33333333  0.        ]]


In [61]:
#HW 3.7 Computing the Inverse of a Matrix

a = np.array([[-1,-2,1,-2],
              [-1,-2,0,1],
              [1,1,-2,-2],
              [-1,-2,2,-2]])

ainv = la.inv(a)
print(ainv)

[[-6.00000000e+00  2.00000000e+00  2.00000000e+00  5.00000000e+00]
 [ 2.66666667e+00 -1.33333333e+00 -1.00000000e+00 -2.33333333e+00]
 [-1.00000000e+00 -5.55111512e-17 -0.00000000e+00  1.00000000e+00]
 [-6.66666667e-01  3.33333333e-01  0.00000000e+00  3.33333333e-01]]
